config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  devise_for :users
  root 'home#index'
  resources :photos do

  member do
    put "like", to: "photos#upvote"
    put "dislike", to: "photos#downvote"
  end
end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
end

app/models/image_uploader.rb
class ImageUploader < Shrine
  # plugins and uploading logic
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user


include ImageUploader::Attachment.new(:image)
  acts_as_votable

  def self.search(search)
    where("name LIKE ? OR location LIKE ?",  "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :photo
end

# # The people who follow us
#   has_and_belongs_to_many :followers, class_name: 'User', join_table: :followers,
#   foreign_key: :followed_id, association_foreign_key: :follower_id
#
#   # The people we follow
#   has_and_belongs_to_many :following, class_name: 'User', join_table: :followers,
#   foreign_key: :follower_id, association_foreign_key: :followed_id

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end
  # GET /photos/1
  # GET /photos/1.json
  def show
  end
  # GET /photos/new
  def new
    @photo = Photo.new
  end
  # GET /photos/1/edit
  def edit
  end
  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    # @photo.save
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  def upvote
  @photo = Photo.find(params[:id])
  @photo.upvote_by current_user

  redirect_back fallback_location: root_path
  end

  def downvote
  @photo = Photo.find(params[:id])
  @photo.downvote_by current_user

  redirect_back fallback_location: root_path
  end

  def index
  @photos = Photo.all
  if params[:search]
    @photos = Photo.search(params[:search]).order("created_at DESC")
  else
    @photos = Photo.all.order("created_at DESC")
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image_data, :user_id, :caption, :image)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<ul class="nav justify-content-center">
  <li class="nav-item">
    <% if user_signed_in? %>
      <%= link_to 'Logout' , destroy_user_session_path, method: :delete %>
    <% end %>

  </li>
</ul>


<!-- <a href="/photos">Please click here to see photos.</a> -->

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Welcome to Sanagram</h1>
    <%= link_to "Please click here to see photos." , photos_path, class: "btn btn-danger"%>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


<div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

  <%= form.hidden_field :image, value: @photo.cached_image_data if defined? (@photo.cached_image_data) %>
  <%= form.file_field :image %>

  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :photo_user_id %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :photo_caption %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

<h1>Welcome to lala land</h1>

</div>


<div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
          <!-- <a href="#" class="thumbnail"> -->
          <%= image_tag(photo.image_url, width: "100%", height: "100%")%>
          <!-- </a> -->
          <p>  <%= photo.caption %></p>
          <p>
          <%= link_to like_photo_path(photo), method: :put do %>
            Like
            <%= photo.get_upvotes.size %>
          <% end %>

          <%= link_to dislike_photo_path(photo), method: :put do %>
            Dislike
            <%= photo.get_downvotes.size %>
        </p>
        </div>

        <% end %>




        <!-- </td> -->
        <% if @photos.blank? %>
          <h4>There are no photos containing the term <%= params[:search] %>.</h4>
        <% end %>

    <% end %>
</div>

<%= link_to ' Click here to upload New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>Click here to upload new photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <img src="<%= @photo.image_url %>">
  <!-- <strong>Image data:</strong> -->

</p>

<p>
  <strong>User:</strong>
  <%= @photo.user %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @photo.caption %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>